version: "3.7"

volumes:
  logs:
    driver: local

services:
  shortener_api:
    container_name: shortener_api
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    command: php -S 0.0.0.0:8100 -t public
    environment:
      docker: "true"
    ports:
      - "8100:8100"
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    network_mode: "mysql_default"